# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Lee
email: james@kcbighuge.com
description: > # this means to ignore newlines until "baseurl:"
  Less than all things about data, finance, tech, science, and sports
  (K.C. teams, mostly).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kcbighuge.com" # the base hostname & protocol for your site
twitter_username: kcbighuge
github_username:  kcbighuge
linkedin_username:  jjleekc

# Build settings
markdown: kramdown
